In [200]:
import numpy as np
import requests

In [201]:
submission_data = np.load("data/DefenseTransformationSubmit.npz")

In [202]:
x = np.copy(submission_data["representations"])

In [203]:
x

array([[-0.41137788,  0.4000075 , -4.827531  , ...,  3.5404382 ,
        -1.6436763 ,  5.8219237 ],
       [ 6.4583564 , -1.3471384 ,  1.0382332 , ...,  2.014428  ,
         0.12205873,  6.9350157 ],
       [-1.3121728 ,  3.8473153 , -5.2651067 , ...,  5.1495447 ,
        -0.09182018, 10.406213  ],
       ...,
       [ 0.06124209, -1.9601537 , -3.0058804 , ...,  3.049747  ,
        -2.1587384 ,  3.2355242 ],
       [-4.7244005 , -4.2666435 , -0.01628606, ..., -1.4774249 ,
        -0.5290377 , -0.89313024],
       [-2.1124403 ,  2.15437   , -3.430675  , ...,  0.07397635,
        -1.4612014 ,  7.750743  ]], dtype=float32)

In [204]:
for i in range(len(x)):
    x[i] = np.random.permutation(x[i])

In [205]:
x

array([[ 7.2920504 , -2.2139425 , -0.7261216 , ..., -4.794177  ,
         1.2168627 ,  1.5732837 ],
       [ 3.8454964 , -1.3434855 ,  1.7816075 , ...,  0.49228036,
        -7.535404  ,  1.7949451 ],
       [ 0.37539783,  0.3690339 , -1.6679293 , ..., -0.98342043,
        -5.274282  ,  2.8250072 ],
       ...,
       [-7.516942  ,  3.5818074 , -2.6716056 , ..., -1.3715059 ,
        -2.1587384 , -1.5777184 ],
       [-2.542913  , -5.3173847 , -1.9967324 , ..., -3.4231791 ,
         6.2681065 ,  1.3711029 ],
       [-5.466727  ,  0.9629428 , -1.2141567 , ...,  3.0907547 ,
        -5.2484894 , -0.49322864]], dtype=float32)

In [206]:
gauss = np.random.normal(0, 0.5, (20250, 192))

In [207]:
mask = np.random.rand(20250, 192) < 0.5

In [208]:
new_array = np.where(mask, x, x + gauss)

In [209]:
new_array

array([[ 7.34659084, -1.47758994, -0.7261216 , ..., -4.91683733,
         1.21686268,  1.77243262],
       [ 3.16813016, -1.41583645,  0.93389741, ...,  0.68910406,
        -7.53540421,  3.2206991 ],
       [ 0.37539783, -0.01631389, -1.89774462, ..., -0.98342043,
        -5.27428198,  2.8250072 ],
       ...,
       [-7.07573645,  3.58180737, -2.67160559, ..., -1.37150586,
        -2.15873837, -1.96793963],
       [-2.37157086, -5.31738472, -1.99673235, ..., -3.35477628,
         4.91806134,  1.37110293],
       [-4.81061898,  0.39385452, -0.83432805, ...,  3.09075475,
        -5.24848938, -0.41901434]])

In [210]:
new_array = new_array.astype(np.float32)

In [211]:
new_array.dtype

dtype('float32')

In [212]:
new_array[0].dtype

dtype('float32')

In [213]:
np.savez(
    "task3sub3.npz",
    representations=new_array,
)

In [175]:
def defense_submit(path_to_npz_file: str):
    endpoint = "/defense/submit"
    url = "http://34.71.138.79:9090" + endpoint
    with open(path_to_npz_file, "rb") as f:
        response = requests.post(url, files={"file": f}, headers={"token": "DdE56eC1EvRwWcuy"})
        
        print(response.status_code)
        print(response.content)
        print(response.json())

In [173]:
defense_submit("task3sub3.npz")

ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

In [75]:
evaluate_data = np.load("data/DefenseTransformationEvaluate.npz")

In [76]:
evaluate_data["labels"]

array([7, 8, 5, ..., 0, 5, 7])

In [176]:
from scipy.spatial import distance