In [200]:
import numpy as np
import requests

In [201]:
submission_data = np.load("data/DefenseTransformationSubmit.npz")

In [202]:
x = np.copy(submission_data["representations"])

In [203]:
x

array([[-0.41137788,  0.4000075 , -4.827531  , ...,  3.5404382 ,
        -1.6436763 ,  5.8219237 ],
       [ 6.4583564 , -1.3471384 ,  1.0382332 , ...,  2.014428  ,
         0.12205873,  6.9350157 ],
       [-1.3121728 ,  3.8473153 , -5.2651067 , ...,  5.1495447 ,
        -0.09182018, 10.406213  ],
       ...,
       [ 0.06124209, -1.9601537 , -3.0058804 , ...,  3.049747  ,
        -2.1587384 ,  3.2355242 ],
       [-4.7244005 , -4.2666435 , -0.01628606, ..., -1.4774249 ,
        -0.5290377 , -0.89313024],
       [-2.1124403 ,  2.15437   , -3.430675  , ...,  0.07397635,
        -1.4612014 ,  7.750743  ]], dtype=float32)

In [215]:
permut = np.random.permutation(len(x[0]))

In [216]:
for i in range(len(x)):
    x[i] = np.array([x[i][j] for j in permut])

In [217]:
x

array([[ 2.8879416 , -0.41137788,  0.4245259 , ...,  0.4000075 ,
        -0.6547244 , -3.4979305 ],
       [-1.1042523 ,  8.896503  , -1.0543176 , ..., -8.315731  ,
         2.95226   , -5.284005  ],
       [ 5.1495447 ,  1.978908  ,  2.177405  , ..., -5.382346  ,
        -1.1103452 ,  5.0714264 ],
       ...,
       [ 0.71590203,  2.8776102 , -1.2704463 , ...,  1.1106582 ,
         1.1434928 ,  0.06124209],
       [-6.320667  , -0.87910724,  2.7892208 , ..., -0.24673705,
        -0.286119  , -4.0610266 ],
       [ 3.8449044 , -0.6349242 ,  3.233258  , ...,  4.0009537 ,
        -4.5234056 , -3.430675  ]], dtype=float32)

In [218]:
gauss = np.random.normal(0, 0.5, (20250, 192))

In [219]:
mask = np.random.rand(20250, 192) < 0.5

In [220]:
new_array = np.where(mask, x, x + gauss)

In [221]:
new_array

array([[ 2.8454094 ,  0.83414573,  0.42452589, ...,  0.40000749,
        -0.65472442, -3.49793053],
       [-1.10425234,  8.89650345, -1.4995098 , ..., -8.31573105,
         2.95226002, -5.28400517],
       [ 5.14954472,  1.82344805,  2.17740512, ..., -5.38234615,
        -2.02614786,  5.07142639],
       ...,
       [ 0.71590203,  2.87761021, -1.2704463 , ...,  1.11065817,
         1.14349282,  0.06124209],
       [-6.83091687, -0.19164789,  3.35209235, ..., -0.24673705,
        -0.28611901, -4.06102657],
       [ 3.84490442, -0.63492417,  3.23325801, ...,  4.00095367,
        -4.52340555, -3.43067503]])

In [222]:
new_array = new_array.astype(np.float32)

In [223]:
new_array.dtype

dtype('float32')

In [224]:
new_array[0].dtype

dtype('float32')

In [225]:
np.savez(
    "AleToTyDzwonisz.npz",
    representations=new_array,
)

In [175]:
def defense_submit(path_to_npz_file: str):
    endpoint = "/defense/submit"
    url = "http://34.71.138.79:9090" + endpoint
    with open(path_to_npz_file, "rb") as f:
        response = requests.post(url, files={"file": f}, headers={"token": "DdE56eC1EvRwWcuy"})
        
        print(response.status_code)
        print(response.content)
        print(response.json())

In [173]:
defense_submit("task3sub3.npz")

ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

In [75]:
evaluate_data = np.load("data/DefenseTransformationEvaluate.npz")

In [76]:
evaluate_data["labels"]

array([7, 8, 5, ..., 0, 5, 7])

In [176]:
from scipy.spatial import distance

In [226]:
sorted(x[0])

[-10.727409,
 -9.584661,
 -8.899271,
 -8.549782,
 -8.435865,
 -8.263282,
 -8.246766,
 -6.440993,
 -6.224608,
 -5.9054446,
 -5.8404527,
 -5.5832043,
 -5.384459,
 -5.2357054,
 -5.1225634,
 -5.080521,
 -5.032033,
 -4.9102216,
 -4.827531,
 -4.794177,
 -4.587634,
 -4.5611753,
 -4.484279,
 -4.0074434,
 -3.9501412,
 -3.7640436,
 -3.7526405,
 -3.7273278,
 -3.63285,
 -3.6300275,
 -3.5827372,
 -3.505954,
 -3.5026886,
 -3.4979305,
 -3.4618297,
 -3.3194501,
 -2.9910734,
 -2.9907198,
 -2.9508386,
 -2.7847896,
 -2.7583294,
 -2.7086022,
 -2.6303713,
 -2.6017785,
 -2.3757055,
 -2.2751133,
 -2.2164373,
 -2.2139425,
 -2.1636574,
 -2.1143947,
 -2.0823271,
 -2.0775502,
 -2.034382,
 -1.9413608,
 -1.9111501,
 -1.7211558,
 -1.7080607,
 -1.6902572,
 -1.66421,
 -1.6436763,
 -1.6338055,
 -1.4511265,
 -1.4321012,
 -1.2755035,
 -1.2701417,
 -1.2502679,
 -1.2359915,
 -1.170262,
 -0.99749297,
 -0.9922593,
 -0.97846377,
 -0.9617523,
 -0.95070976,
 -0.9377578,
 -0.9033767,
 -0.86172086,
 -0.85951287,
 -0.80551887,
 -

In [227]:
sorted(new_array[0])

[-10.727409,
 -10.145864,
 -9.4153385,
 -8.549782,
 -8.435865,
 -8.263282,
 -8.246766,
 -7.20144,
 -6.003219,
 -5.9054446,
 -5.8404527,
 -5.7631106,
 -5.677653,
 -5.665658,
 -5.384459,
 -5.1225634,
 -5.080521,
 -5.032033,
 -4.9102216,
 -4.794177,
 -4.587634,
 -4.484279,
 -4.440681,
 -4.3774476,
 -4.156032,
 -3.9501412,
 -3.8285382,
 -3.7640436,
 -3.63285,
 -3.6300275,
 -3.5827372,
 -3.5219173,
 -3.505954,
 -3.4979305,
 -3.355496,
 -3.2458177,
 -3.112116,
 -3.0965981,
 -3.0500946,
 -2.9910734,
 -2.9694014,
 -2.9508386,
 -2.7639327,
 -2.6017785,
 -2.5156493,
 -2.4952517,
 -2.4449422,
 -2.4275732,
 -2.3757055,
 -2.294095,
 -2.1649044,
 -2.1143947,
 -2.0823271,
 -1.9413608,
 -1.9111501,
 -1.7614763,
 -1.66421,
 -1.6436763,
 -1.6261604,
 -1.5493101,
 -1.4511265,
 -1.4321012,
 -1.4228463,
 -1.3809934,
 -1.2784995,
 -1.2701417,
 -1.2313433,
 -1.170262,
 -0.97846377,
 -0.96930015,
 -0.9617523,
 -0.9377578,
 -0.86172086,
 -0.8241652,
 -0.7974028,
 -0.74720585,
 -0.7261216,
 -0.6646893,
 -0.6547